; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy]
platform = https://github.com/platformio/platform-teensy.git
board = teensymm
framework = arduino
board_build.f_cpu = 600000000L

build_flags =
  -std=c++17
  -Wall
  -O2
  -DCLARINOID_PLATFORM_TEENSY
  -I../../library/clarinoid_core/include

lib_extra_dirs =
  ../../library

lib_deps = 
  clarinoid_core
