; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native32]
platform = windows_x86
platform_packages = toolchain-gccmingw32

lib_extra_dirs =
  ../../library

; https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html
build_flags =
  #-I../../library
  -std=c++17
  -DCLARINOID_PLATFORM_X86
  -Wall
  -O2
  -m32         ; 32-bit code
  -mwindows                 ; <- no console, use WinMain

lib_deps =
  lib_example
