M48
; DRILL file {KiCad 8.0.8} date 2025-02-14T20:36:54+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-14T20:36:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X-1.059Y-2.9096
X-1.059Y-3.2245
T2
X1.2557Y-2.6263
T3
X1.2557Y-3.4137
T4
X-1.069Y-2.5769
M30
